config/routes.rb
Rails.application.routes.draw do
  resources :companies do
    resources :locations
    resources :products do
      resources :reviews
      end
    end
root 'companies#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :locations
  has_many :products
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :company
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :company

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  def index
    @companies = Company.all
  end

  def show
    @company = Company.find(params[:id])
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to company_path(@company)
    else
      render :new
    end
  end


  private

    def company_params
      params.require(:company).permit(:name, :suffix, :catch_phrase, :email, :start_date, :industry)
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def show
    @company = Company.find(params[:company_id])
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
    @company = Company.find(params[:company_id])
  end

  def create
    @company = Company.find(params[:company_id])
    @product = Product.new(product_params)
    @product.company_id = params[:company_id]
    if @product.save
      redirect_to company_path(@company)
    else
      render :new
    end
  end

  private

  def product_params
    params.require(:product).permit(:department, :name, :price)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/_form.html.erb
<%= form_for @company do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :suffix %>
<%= f.text_field :suffix %>

<%= f.label :catch_phrase %>
<%= f.text_field :catch_phrase %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :start_date %>
<%= f.text_field :start_date %>

<%= f.label :industry %>
<%= f.text_field :industry %>

<%= f.submit %>

<% end %>

app/views/companies/index.html.erb
<div class="page-header">
  <h1>Companies</h1>
  <%= link_to "Create New Company", new_company_path, class: "btn btn-info pull-right" %>
</div>
<table>
  <thead>
    <th>Name</th>
    <th>Suffix</th>
    <th>Catch Phrase</th>
    <th>email</th>
    <th>Start Date</th>
    <th>Industry</th>
  </thead>
  <tbody>
    <% @companies.each do |c|  %>
    <tr>
      <td> <%= link_to c.name, c  %></td>
      <td> <%= c.suffix %></td>
      <td> <%= c.catch_phrase %></td>
      <td> <%= c.email %></td>
      <td> <%= c.start_date %></td>
      <td> <%= c.industry %></td>
      <td> <%= link_to "Create new Product", new_company_product_path(c) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/companies/new.html.erb
<h1>Create New Company</h1>
<%= render 'form' %>

app/views/companies/show.html.erb
<table>
  <thead>
    <th>Name</th>
    <th>Suffix</th>
    <th>Catch Phrase</th>
    <th>email</th>
    <th>Start Date</th>
    <th>Industry</th>
  </thead>
  <tbody>
      <tr>
        <td><%= @company.name %></td>
        <td><%= @company.suffix %></td>
        <td><%= @company.catch_phrase %></td>
        <td><%= @company.email %></td>
        <td><%= @company.start_date %></td>
        <td><%= @company.industry %></td>
      </tr>
  </tbody>
</table>
<br>
<table>
  <thead>
    <th>Department</th>
    <th>Name</th>
    <th>Price</th>
    <th>Company Id</th>
  </thead>
  <tbody>
    <% @company.products.each do |p| %>
    <tr>
      <td><%= p.department %></td>
      <td><%= p.name %></td>
      <td><%= p.price %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<br>
<table>
  <thead>
    <th></th>
  </thead>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ArHomework</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for [@company, @product] do |f| %>

  <%= f.label :department %>
  <%= f.text_field :department %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :price %>
  <%= f.text_field :price %>

  <%= f.submit %>

<% end %>

app/views/products/new.html.erb
<h1>Create New Product</h1>
<%= render 'form' %>